image: node:lts-alpine
cache:
  key: '$CI_COMMIT_REF_NAME'
stages:
    - build
    - release
    - deploy
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://172.16.120.101:2375 
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  tags: 
    - FRONTEND
  script:
     - npm install -g http-server 
     - npm install 
     - npm run-script build
  artifacts:
    paths:
      - /builds/front-end/huami-frontend/dist
    expire_in: 3 day

release:
  stage: release 
  tags:
    - FRONTEND
  variables:
     REGISTRY_URL: .ir/dev/frontend/whoami
  dependencies:
    - build
  image: docker:dind
  before_script:  
    - echo -en "FROM .ir/devops/nginx\nCOPY dist/ ./ \n" > nginx
  script: 
     - docker build -f nginx -t $REGISTRY_URL .
     - docker push $REGISTRY_URL
deploy_dev_whoami_frontend:
  stage: deploy
  tags:
    - FRONTEND
  variables:
     REGISTRY_URL: .ir/dev/frontend/whoami
  image: .ir/devops/basecd
  before_script:
    - ssh dev0@172.16.120.101 "docker rm -f whoami_frontend"  || true
    - echo -en "\n\n YOUR ADDRESS! .ir \n\n"
  script:
    #test
    - ssh dev0@172.16.120.101 "docker pull $REGISTRY_URL && docker tag $REGISTRY_URL whoami_frontend && echo $? "
    - ssh dev0@172.16.120.101 "docker run -d  --name whoami_frontend -p 8085:80  whoami_frontend   "
    - ssh dev0@172.16.120.101 "sleep 7 && curl -I .ir -L -k   " 
    - tput setaf 2 ; echo -en "\n\n\.ir\n\n  " 
